// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtg2KSu2WFtnHNDEXDQ4RCuiA1RbqFbp4',
    appId: '1:725596583677:web:51fb66b002625a88f33094',
    messagingSenderId: '725596583677',
    projectId: 'fir-62b5f',
    authDomain: 'fir-62b5f.firebaseapp.com',
    storageBucket: 'fir-62b5f.appspot.com',
    measurementId: 'G-KHWM8BL23M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJlH22SD2QiXfZtKXWWPPOmLpB90uJl70',
    appId: '1:725596583677:android:f8152cc9dcc2d9b9f33094',
    messagingSenderId: '725596583677',
    projectId: 'fir-62b5f',
    storageBucket: 'fir-62b5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYJQYxnRd9kWm0AmD7DjAlzPaMB8N3aTk',
    appId: '1:725596583677:ios:dcc859fbdc466a43f33094',
    messagingSenderId: '725596583677',
    projectId: 'fir-62b5f',
    storageBucket: 'fir-62b5f.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYJQYxnRd9kWm0AmD7DjAlzPaMB8N3aTk',
    appId: '1:725596583677:ios:dcc859fbdc466a43f33094',
    messagingSenderId: '725596583677',
    projectId: 'fir-62b5f',
    storageBucket: 'fir-62b5f.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtg2KSu2WFtnHNDEXDQ4RCuiA1RbqFbp4',
    appId: '1:725596583677:web:0fd51b16ed929bf8f33094',
    messagingSenderId: '725596583677',
    projectId: 'fir-62b5f',
    authDomain: 'fir-62b5f.firebaseapp.com',
    storageBucket: 'fir-62b5f.appspot.com',
    measurementId: 'G-5L0VZ9CJED',
  );
}
